version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: techni-zlecenia
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  db_data:

networks:
  internal:
