POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "username":"reoh",
    "credentials": {
        "password":"reoh1234",
        "email":"u110_lukdab_waw@technischools.com"
    }
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "credentials": {
        "password":"reoh1234",
        "email":"u110_lukdab_waw@technischools.com"
    }
}

###

POST http://localhost:3000/auth/refresh